name: Deploy
  on:
    push:
    workflow_dispatch:
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      
    - name: 🗜️ Minify
      uses: nizarmah/auto-minify@v2.1

    - name: 📩 Deploy to custom domain
      if: ${{inputs.staging == false}}
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: https://greenvisionmedia.com  
        username: gvm@$greenvisionmedia.com
        password: ${{secrets.ftp}}
        server-dir: greenvisionmedia.com/public_html/
        protocol: ftps
